In [9]:
# Find missing calibrations, and calibrations with large median error
import os
import pandas as pd

# Load the calibration_info.csv file
calibrations_info = pd.read_csv('calibration_info.csv')
calibrations_info

,UniqueId,Name,Location,res_mean,res_median,res_std,res_max,res_min,gamma,kappa,...,lam,mup,sigp,rsmax,alpha,alpha1,alpha2,betam1,n,kappa_k
0,64,"Ono et al. 1989, CA025C",81828011-5b4b-4138-be69-3a1c47544fdf-007,0.056469,0.056308,0.000949,0.063178,0.054899,1.967600,1.072573,...,0.197418,6.702280,5.041588,0.991795,0.000617,0.364006,0.205205,0.020377,4.337753,0.249056
1,352,"Kunnath et al. 1997, A8",97dd05ce-a541-46a1-a5d2-5d5bf654cb6f-007,0.064116,0.064054,0.000396,0.066460,0.063446,0.349804,0.900517,...,0.840812,4.203175,5.221884,0.957630,0.004986,2.381744,0.327617,0.000686,2.661915,2.937689
2,379,"Sritharan et al. 1995, IC3",a815a3bf-1b81-4ae7-89dd-10555c1e48b0-007,0.086166,0.086095,0.001848,0.092875,0.080608,0.292919,1.001421,...,0.509318,2.958336,1.721987,0.994618,0.000254,6.175635,0.825094,0.000144,1.270288,4.382527
3,374,"Calderone et al. 2000, 328",f9585614-d99f-4ffe-8606-959791148bc5-007,0.069248,0.069533,0.002651,0.076363,0.061858,1.347681,1.065720,...,0.615313,1.344393,0.478505,0.658248,0.010387,3.755908,0.264980,0.005546,3.553621,0.336679
4,309,"NIST, Model N2",042badac-3f82-492d-9b57-ed6589371140-007,0.108375,0.108311,0.002932,0.118100,0.101374,1.432812,1.098083,...,0.242712,0.991950,0.496090,0.662467,0.000051,5.461077,1.802729,0.013241,1.412692,0.506857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,296,"Wong et al. 1990, No. 1",95cdf547-4bc5-4446-aa3c-69faf07428bc-007,0.036741,0.036658,0.000849,0.039880,0.034734,1.730851,1.067936,...,0.367635,1.048165,0.646686,0.627773,0.000683,8.788212,0.405909,0.007076,3.194312,0.379581
274,150,"Xiao and Martirossyan 1998, HC4-8L16-T6-0.2P",a934abc3-fc95-4d0e-b9fb-c9e3c38d72d9-007,0.054078,0.053963,0.001310,0.059298,0.051321,0.536764,0.979217,...,0.569966,0.258854,0.455643,0.226642,0.020408,0.412493,0.199977,0.010005,7.255161,0.458122
275,3,"Gill et al. 1979, No. 3",45050e4d-7a8d-4ec3-a487-0ca4baadf60d-007,0.041197,0.040961,0.001350,0.047497,0.038672,1.672603,1.006966,...,0.354028,1.605912,0.526656,0.711750,0.000260,1.555760,1.670239,0.001850,2.256011,1.153229
276,336,"Arakawa et al. 1988, No. 19",50fbc6cb-0128-4011-81bb-acab851f1a86-007,0.050266,0.050073,0.001445,0.055338,0.046967,1.002111,1.058914,...,0.085019,2.084247,4.240102,0.939044,0.000839,0.898241,0.045689,0.014780,3.288769,0.465055
277,199,"Aboutaha et al. 1999, SC3",d4d1229c-f159-40b1-80c2-1e86661dd038-007,0.054580,0.054482,0.000861,0.059408,0.052689,1.694378,1.071409,...,0.098701,2.246850,1.808366,0.998307,0.001135,5.129890,0.060567,0.032061,4.850393,0.217448

In [10]:
# Load the calibrations_log.csv file inside quoFEM_TMCMC folder
calibrations_log = pd.read_csv(os.path.join('quoFEM_TMCMC', 'calibrations_log.csv'))
calibrations_log.head()

   calId  UniqueId  npts    folder
0      0       222   242  test_222
1      1       367   308  test_367
2      2       275   539  test_275
3      3       330   209  test_330
4      4        19   198  test_019

In [11]:
# Find missing UniqueIds in the calibrations_info file
missing_unique_ids = set(calibrations_log['UniqueId']) - set(calibrations_info['UniqueId'])
#print(f"Missing UniqueIds: {missing_unique_ids}")

# Print the rows for the missing Ids
missing_rows = calibrations_log[calibrations_log['UniqueId'].isin(missing_unique_ids)]
print(f"Missing rows:\n{missing_rows}")

# Print how many missing UniqueIds there are
print(f"Number of missing UniqueIds: {len(missing_unique_ids)}")

Missing rows:
     calId  UniqueId  npts    folder
25      25       280   429  test_280
103    103         9   143  test_009
117    117       209   506  test_209
123    123        49   506  test_049
126    126       194   737  test_194
204    204       143   550  test_143
211    211       180   209  test_180
215    215       207   396  test_207
227    227       332   275  test_332
239    239       241   572  test_241
275    275       364   539  test_364
281    281       325   209  test_325
287    287        77   231  test_077
Number of missing UniqueIds: 13

In [12]:
# Print the list of calId for the missing UniqueId
missing_rows['calId'].values

array([ 25, 103, 117, 123, 126, 204, 211, 215, 227, 239, 275, 281, 287],
      dtype=int64)

In [13]:
# Find UniqueIds with median error greater than 0.1 in the calibrations_info file
high_error_unique_ids = calibrations_info[calibrations_info['res_median'] > 0.1]['UniqueId']
print(f"UniqueIds with median error greater than 0.1: {high_error_unique_ids.tolist()}")

# Print how many UniqueIds have median error greater than 0.1
print(f"Number of UniqueIds with median error greater than 0.1: {len(high_error_unique_ids)}")

UniqueIds with median error greater than 0.1: [309, 196, 217, 15, 216, 302, 381, 195, 204, 205, 366, 98, 99, 345, 47, 28, 380, 340, 206, 193, 147, 117, 245, 189]
Number of UniqueIds with median error greater than 0.1: 24

In [14]:
# Add sets of missing UniqueIds and high error UniqueIds
combined_unique_ids = missing_unique_ids.union(set(high_error_unique_ids))
print(f"Combined UniqueIds (missing or high error): {combined_unique_ids}")

# Print how many UniqueIds are in the combined set
print(f"Number of UniqueIds in combined set: {len(combined_unique_ids)}")

Combined UniqueIds (missing or high error): {9, 143, 15, 147, 280, 28, 302, 47, 49, 180, 309, 189, 193, 194, 195, 196, 325, 332, 77, 204, 207, 205, 209, 206, 340, 216, 345, 217, 98, 99, 364, 366, 241, 117, 245, 380, 381}
Number of UniqueIds in combined set: 37

In [15]:
# Find the UniqueIds in the combined set in the calibrations_log file and extract the correspoding calId for each one and put in a list
calibration_ids = [calibrations_log[calibrations_log['UniqueId'] == unique_id]['calId'].values[0] for unique_id in combined_unique_ids]
# print(f"Calibration IDs for combined UniqueIds: {calibration_ids}")

# Print the combined set of UniqueIds as a list 10 at a time
for i in range(0, len(calibration_ids), 10):
    print(list(calibration_ids)[i:i+10])
    #print(list(combined_unique_ids)[i:i+10])

[103, 204, 19, 54, 25, 134, 155, 199, 123, 211]
[284, 10, 36, 126, 97, 216, 281, 227, 287, 96]
[215, 128, 117, 150, 127, 236, 234, 267, 288, 223]
[275, 73, 239, 86, 91, 168, 200]